services:
  - type: web
    name: digital-subdesk
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        value: subdesk_secret_render_production
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        sync: false
      - key: WA_NUMBER
        value: "880XXXXXXXXX"
      - key: FB_PAGE
        value: https://web.facebook.com/subdeskofficial
